### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nevotheless** [aesopwaits/GPSChat#1]
Heyho, i just found your little project here and maybe want to use it as the base for another project i may start working on. 

But... i cannot find a license file. Can you please add a license file to your project so that everyone knows if its allowed to use your code?

**Comment by joshuakopman** [comment]
Hey man, added a standard MIT license. FYI if you're testing the repository out, be aware that the javascript navigator API has been deprecated under HTTP in Chrome. The gps coordinate client-side functionality will only work under https in the latest version. Definitely curious about your project, let me know how it turns out or if you have any questions!

**Comment by nevotheless** [comment]
Thanks! I'll as far as i have something to show off.
